# coding:utf-8

# 权限样式 app_权限名字
perm_dic = {
    'crm_views_customer_detail': ['customer_detail', 'GET', []],
    'crm_edit_own_customer_info': ['customer_detail', 'POST', []],
    'crm_view_customer_enro': ['cus_enroll', 'GET', []],
    'crm_edit_customer_enro': ['cus_enroll', 'POST', []],
    'crm_view_enro_done': ['enroll_done', 'GET', []],
    'crm_edit_enro_done': ['enroll_done', 'POST', []],
    'crm_view_tracking': ['tracking', 'GET', []],
    'crm_view_library': ['customers_library', 'GET', []],
    'crm_view_signed': ['signed', 'GET', []],
    'crm_view_classlist': ['class_list', 'GET', []],
    'crm_view_statistical': ['statistical', 'GET', []],
    'crm_view_classdetail': ['class_detail', 'GET', []],
    'crm_edit_classdetail': ['class_detail', 'POST', []],
    'crm_view_consult_record': ['consult_record', 'GET', []],
    'crm_edit_consult_record': ['consult_record', 'POST', []],
    'crm_view_addcustomer': ['addcustomer', 'GET', []],
    'crm_edit_addcustomer': ['addcustomer', 'POST', []],
    'crm_view_add_referral_customer': ['add_referral_customer', 'GET', []],
    'crm_edit_add_referral_customer': ['add_referral_customer', 'POST', []],
    'crm_view_add_push_customer': ['add_push_customer', 'GET', []],
    'crm_edit_add_push_customer': ['add_push_customer', 'POST', []],
    'crm_view_dashboard': ['dashboard', 'GET', []],
    'crm_view_enrollment': ['enrollment', 'GET', []],
    'crm_edit_enrollment': ['enrollment', 'POST', []],
    'crm_view_payment': ['payment', 'GET', []],
    'crm_edit_payment': ['payment', 'POST', []],
    'crm_view_punishment': ['punishment', 'GET', []],
    'crm_view_showchannels': ['showchannels', 'POST', []],
    'crm_view_addchannel': ['addchannel', 'POST', []],
    'crm_edit_addchannel': ['addchannel', 'POST', []],
    'crm_view_addlinkman': ['addlinkman', 'POST', []],
    'crm_edit_addlinkman': ['addlinkman', 'POST', []],
    'crm_view_addprogress': ['addprogress', 'POST', []],
    'crm_edit_addprogress': ['addprogress', 'POST', []],
    'crm_view_channel_detail': ['channel_detail', 'POST', []],
    'crm_edit_channel_detail': ['channel_detail', 'POST', []],
    'crm_view_linkman_detail': ['linkman_detail', 'POST', []],
    'crm_edit_linkman_detail': ['linkman_detail', 'POST', []],
    'crm_view_progress_detail': ['progress_detail', 'POST', []],
    'crm_edit_progress_detail': ['progress_detail', 'POST', []],


    'teacher_view_teacher_dashboard': ['teacher_dashboard', 'GET', []],
    'teacher_view_classlist': ['classlist', 'GET', []],
    'teacher_view_courselist': ['courselist', 'GET', []],
    'teacher_edit_courselist': ['courselist', 'POST', []],
    'teacher_view_courserecord': ['courserecord', 'GET', []],
    'teacher_edit_courserecord': ['courserecord', 'POST', []],
    'teacher_view_createcourse': ['createcourse', 'GET', []],
    'teacher_edit_createcourse': ['createcourse', 'POST', []],
    'teacher_view_editcourse': ['editcourse', 'GET', []],
    'teacher_edit_editcourse': ['editcourse', 'POST', []],
    'teacher_view_studentinformation': ['studentinformation', 'GET', []],
    'teacher_edit_studentinformation': ['studentinformation', 'POST', []],
    'teacher_view_study_consult_record': ['study_consult_record', 'GET', []],
    'teacher_edit_study_consult_record': ['study_consult_record', 'POST', []],
    'teacher_view_coursedetail': ['coursedetail', 'GET', []],
}