# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-04 16:27
from __future__ import unicode_literals

import core.adminlte.constants
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.manager
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0007_alter_validators_add_error_messages'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='\u6570\u636e\u521b\u5efa\u65f6\u95f4')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='\u6570\u636e\u66f4\u65b0\u65f6\u95f4')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='\u6570\u636e\u5220\u9664\u65f6\u95f4')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='\u83dc\u5355\u540d\u79f0')),
                ('icon', models.CharField(default=b'fa-circle-o', help_text='\u53c2\u8003:http://fontawesome.io', max_length=50, verbose_name='\u83dc\u5355\u56fe\u6807')),
                ('app_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='App\u540d\u79f0')),
                ('model_name', models.CharField(blank=True, help_text='\u6ce8\u610f\u5927\u5c0f\u5199', max_length=200, null=True, verbose_name='Model\u540d\u79f0')),
                ('url', models.CharField(blank=True, help_text='\u9009\u586b', max_length=200, null=True, verbose_name='\u5168\u8def\u5f84')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='\u6392\u5e8f')),
                ('status', models.PositiveSmallIntegerField(choices=[(0, '\u7981\u7528'), (1, '\u542f\u7528'), (99, '\u5220\u9664')], db_index=True, default=1, verbose_name='\u72b6\u6001')),
                ('lft', models.PositiveIntegerField(db_index=True, editable=False)),
                ('rght', models.PositiveIntegerField(db_index=True, editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(db_index=True, editable=False)),
            ],
            options={
                'ordering': ('order',),
                'verbose_name': '\u83dc\u5355',
                'verbose_name_plural': '\u83dc\u5355',
            },
            bases=(models.Model, core.adminlte.constants.UsableStatus),
            managers=[
                ('_default_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='\u6570\u636e\u521b\u5efa\u65f6\u95f4')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='\u6570\u636e\u66f4\u65b0\u65f6\u95f4')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='\u6570\u636e\u5220\u9664\u65f6\u95f4')),
                ('status', models.PositiveSmallIntegerField(choices=[(0, '\u7981\u7528'), (1, '\u542f\u7528'), (99, '\u5220\u9664')], db_index=True, default=1, verbose_name='\u72b6\u6001')),
            ],
            options={
                'verbose_name': '\u6743\u9650',
                'verbose_name_plural': '\u6743\u9650',
            },
            bases=(models.Model, core.adminlte.constants.UsableStatus),
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='\u6570\u636e\u521b\u5efa\u65f6\u95f4')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='\u6570\u636e\u66f4\u65b0\u65f6\u95f4')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='\u6570\u636e\u5220\u9664\u65f6\u95f4')),
                ('name', models.CharField(max_length=50, verbose_name='\u8d44\u6e90\u540d\u79f0')),
                ('app_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='\u6240\u5c5e\u5e94\u7528')),
                ('model_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='\u6240\u5c5e\u6a21\u578b')),
                ('url', models.CharField(blank=True, help_text='API\u5730\u5740', max_length=500, null=True, verbose_name='\u8d44\u6e90\u5730\u5740')),
                ('note', models.CharField(blank=True, max_length=500, null=True, verbose_name='\u5907\u6ce8')),
                ('status', models.PositiveSmallIntegerField(choices=[(0, '\u7981\u7528'), (1, '\u542f\u7528'), (99, '\u5220\u9664')], db_index=True, default=1, verbose_name='\u72b6\u6001')),
            ],
            options={
                'verbose_name': 'API\u8d44\u6e90',
                'verbose_name_plural': 'API\u8d44\u6e90',
            },
            bases=(models.Model, core.adminlte.constants.UsableStatus),
        ),
        migrations.CreateModel(
            name='SystemConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='\u6570\u636e\u521b\u5efa\u65f6\u95f4')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='\u6570\u636e\u66f4\u65b0\u65f6\u95f4')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='\u6570\u636e\u5220\u9664\u65f6\u95f4')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='\u952e')),
                ('value', models.CharField(max_length=255, verbose_name='\u503c')),
                ('title', models.CharField(max_length=255, verbose_name='\u63cf\u8ff0')),
                ('status', models.PositiveSmallIntegerField(choices=[(0, '\u7981\u7528'), (1, '\u542f\u7528'), (99, '\u5220\u9664')], db_index=True, default=1, verbose_name='\u72b6\u6001')),
                ('lft', models.PositiveIntegerField(db_index=True, editable=False)),
                ('rght', models.PositiveIntegerField(db_index=True, editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(db_index=True, editable=False)),
            ],
            options={
                'verbose_name': '\u53c2\u6570\u914d\u7f6e',
                'verbose_name_plural': '\u53c2\u6570\u914d\u7f6e',
            },
            bases=(models.Model, core.adminlte.constants.UsableStatus),
            managers=[
                ('_default_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='LteGroup',
            fields=[
            ],
            options={
                'verbose_name': '\u89d2\u8272',
                'proxy': True,
                'verbose_name_plural': '\u89d2\u8272',
            },
            bases=('auth.group',),
            managers=[
                ('objects', django.contrib.auth.models.GroupManager()),
            ],
        ),
    ]
