# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-11 14:56
from __future__ import unicode_literals

import core.adminlte.web_models.constants
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import django.utils.timezone
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0007_alter_validators_add_error_messages'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name=b'email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, verbose_name='\u6d3b\u8dc3')),
                ('is_admin', models.BooleanField(default=False, verbose_name='\u8d85\u7ea7\u7ba1\u7406\u5458')),
                ('name', models.CharField(max_length=32, verbose_name='\u540d\u5b57')),
                ('department', models.CharField(blank=True, default=None, max_length=32, null=True, verbose_name='\u90e8\u95e8')),
                ('tel', models.CharField(blank=True, default=None, max_length=32, null=True, verbose_name='\u5ea7\u673a')),
                ('mobile', models.CharField(blank=True, default=None, max_length=32, null=True, verbose_name='\u624b\u673a')),
                ('memo', models.TextField(blank=True, default=None, null=True, verbose_name='\u5907\u6ce8')),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('valid_begin_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('valid_end_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('avatar', models.ImageField(blank=True, default=None, null=True, upload_to=b'adminlte/user_avatar', verbose_name='\u5934\u50cf')),
            ],
            options={
                'verbose_name': '\u7528\u6237\u4fe1\u606f',
                'verbose_name_plural': '\u7528\u6237\u4fe1\u606f',
            },
        ),
        migrations.CreateModel(
            name='Groups',
            fields=[
                ('group_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auth.Group')),
            ],
            bases=('auth.group',),
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='\u6570\u636e\u521b\u5efa\u65f6\u95f4')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='\u6570\u636e\u66f4\u65b0\u65f6\u95f4')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='\u6570\u636e\u5220\u9664\u65f6\u95f4')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='\u83dc\u5355\u540d\u79f0')),
                ('icon', models.CharField(default=b'fa-circle-o', help_text='\u53c2\u8003:http://fontawesome.io', max_length=50, verbose_name='\u83dc\u5355\u56fe\u6807')),
                ('app_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='\u6240\u5c5e\u5e94\u7528')),
                ('model_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='\u6240\u5c5e\u6a21\u578b')),
                ('url', models.CharField(blank=True, help_text='\u9009\u586b', max_length=200, null=True, verbose_name='\u5168\u8def\u5f84')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='\u6392\u5e8f')),
                ('status', models.PositiveSmallIntegerField(choices=[(0, '\u7981\u7528'), (1, '\u542f\u7528'), (99, '\u5220\u9664')], db_index=True, default=1, verbose_name='\u72b6\u6001')),
                ('lft', models.PositiveIntegerField(db_index=True, editable=False)),
                ('rght', models.PositiveIntegerField(db_index=True, editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(db_index=True, editable=False)),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u6570\u636e\u66f4\u65b0\u4eba')),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='adminlte.Menu', verbose_name='\u4e0a\u7ea7\u83dc\u5355')),
            ],
            options={
                'ordering': ('order',),
                'verbose_name': '\u57fa\u7840-\u83dc\u5355',
                'verbose_name_plural': '\u57fa\u7840-\u83dc\u5355',
            },
            bases=(models.Model, core.adminlte.web_models.constants.UsableStatus),
            managers=[
                ('_default_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='\u6570\u636e\u521b\u5efa\u65f6\u95f4')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='\u6570\u636e\u66f4\u65b0\u65f6\u95f4')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='\u6570\u636e\u5220\u9664\u65f6\u95f4')),
                ('status', models.PositiveSmallIntegerField(choices=[(0, '\u7981\u7528'), (1, '\u542f\u7528'), (99, '\u5220\u9664')], db_index=True, default=1, verbose_name='\u72b6\u6001')),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u6570\u636e\u66f4\u65b0\u4eba')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_permission', to='adminlte.Groups', verbose_name='\u89d2\u8272')),
                ('menus', models.ManyToManyField(blank=True, to='adminlte.Menu', verbose_name='\u83dc\u5355')),
            ],
            options={
                'verbose_name': '\u57fa\u7840-\u9996\u8981\u914d\u7f6e-\u6743\u9650',
                'verbose_name_plural': '\u57fa\u7840-\u9996\u8981\u914d\u7f6e-\u6743\u9650',
            },
            bases=(models.Model, core.adminlte.web_models.constants.UsableStatus),
        ),
        migrations.CreateModel(
            name='Permission_Api_Action',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(help_text='\u5728\u4f20\u5165 api \u4e2d action \u662f\u5fc5\u586b\u9879\u76ee', max_length=255, verbose_name='\u65b9\u6cd5')),
                ('Type', models.PositiveSmallIntegerField(blank=True, choices=[(0, 'get'), (1, 'post')], null=True, verbose_name='\u8bf7\u6c42\u7c7b\u578b')),
                ('memo', models.TextField(blank=True, help_text='\u65b9\u6cd5\u5907\u6ce8', null=True, verbose_name='\u5907\u6ce8')),
                ('status', models.PositiveSmallIntegerField(choices=[(0, '\u7981\u7528'), (1, '\u542f\u7528'), (99, '\u5220\u9664')], db_index=True, default=1, verbose_name='\u72b6\u6001')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='\u6570\u636e\u521b\u5efa\u65f6\u95f4')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='\u6570\u636e\u66f4\u65b0\u65f6\u95f4')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='\u6570\u636e\u5220\u9664\u65f6\u95f4')),
            ],
            options={
                'verbose_name': '\u57fa\u7840-api\u5c42-\u914d\u7f6e',
                'verbose_name_plural': '\u57fa\u7840-api\u5c42-\u914d\u7f6e',
            },
            bases=(models.Model, core.adminlte.web_models.constants.UsableStatus),
        ),
        migrations.CreateModel(
            name='Permission_Api_objects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_name', models.CharField(help_text='\u5728\u4f20\u5165 api \u4e2d action_name \u662f\u5fc5\u586b\u9879\u76ee', max_length=255, unique=True, verbose_name='\u8c03\u7528 \u65b9\u6cd5\u540d\u79f0')),
                ('memo', models.TextField(blank=True, help_text='\u65b9\u6cd5\u5907\u6ce8', null=True, verbose_name='\u5907\u6ce8')),
                ('status', models.PositiveSmallIntegerField(choices=[(0, '\u7981\u7528'), (1, '\u542f\u7528'), (99, '\u5220\u9664')], db_index=True, default=1, verbose_name='\u72b6\u6001')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='\u6570\u636e\u521b\u5efa\u65f6\u95f4')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='\u6570\u636e\u66f4\u65b0\u65f6\u95f4')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='\u6570\u636e\u5220\u9664\u65f6\u95f4')),
            ],
            options={
                'verbose_name': '\u57fa\u7840-api\u5c42-\u57fa\u7840\u914d\u7f6e',
                'verbose_name_plural': '\u57fa\u7840-api\u5c42-\u57fa\u7840\u914d\u7f6e',
            },
            bases=(models.Model, core.adminlte.web_models.constants.UsableStatus),
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='\u6570\u636e\u521b\u5efa\u65f6\u95f4')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='\u6570\u636e\u66f4\u65b0\u65f6\u95f4')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='\u6570\u636e\u5220\u9664\u65f6\u95f4')),
                ('name', models.CharField(max_length=50, verbose_name='\u8d44\u6e90\u540d\u79f0')),
                ('app_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='\u6240\u5c5e\u5e94\u7528')),
                ('model_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='\u6240\u5c5e\u6a21\u578b')),
                ('url', models.CharField(blank=True, help_text='API\u5730\u5740', max_length=500, null=True, verbose_name='\u8d44\u6e90\u5730\u5740')),
                ('note', models.CharField(blank=True, max_length=500, null=True, verbose_name='\u5907\u6ce8')),
                ('status', models.PositiveSmallIntegerField(choices=[(0, '\u7981\u7528'), (1, '\u542f\u7528'), (99, '\u5220\u9664')], db_index=True, default=1, verbose_name='\u72b6\u6001')),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u6570\u636e\u66f4\u65b0\u4eba')),
            ],
            options={
                'verbose_name': '\u57fa\u7840-\u8d44\u6e90',
                'verbose_name_plural': '\u57fa\u7840-\u8d44\u6e90',
            },
            bases=(models.Model, core.adminlte.web_models.constants.UsableStatus),
        ),
        migrations.CreateModel(
            name='SystemConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='\u6570\u636e\u521b\u5efa\u65f6\u95f4')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='\u6570\u636e\u66f4\u65b0\u65f6\u95f4')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='\u6570\u636e\u5220\u9664\u65f6\u95f4')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='\u952e')),
                ('value', models.CharField(max_length=255, verbose_name='\u503c')),
                ('title', models.CharField(max_length=255, verbose_name='\u63cf\u8ff0')),
                ('status', models.PositiveSmallIntegerField(choices=[(0, '\u7981\u7528'), (1, '\u542f\u7528'), (99, '\u5220\u9664')], db_index=True, default=1, verbose_name='\u72b6\u6001')),
                ('lft', models.PositiveIntegerField(db_index=True, editable=False)),
                ('rght', models.PositiveIntegerField(db_index=True, editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(db_index=True, editable=False)),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u6570\u636e\u66f4\u65b0\u4eba')),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='adminlte.SystemConfig', verbose_name='\u7236\u914d\u7f6e\u9879')),
            ],
            options={
                'verbose_name': '\u57fa\u7840-\u53c2\u6570\u914d\u7f6e',
                'verbose_name_plural': '\u57fa\u7840-\u53c2\u6570\u914d\u7f6e',
            },
            bases=(models.Model, core.adminlte.web_models.constants.UsableStatus),
            managers=[
                ('_default_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='permission_api_action',
            name='action_objects',
            field=models.ForeignKey(help_text='\u5728\u4f20\u5165 api \u4e2d action_name \u7684 objects \u65b9\u6cd5 \u662f\u5fc5\u586b\u9879\u76ee', on_delete=django.db.models.deletion.CASCADE, related_name='Api_objects', to='adminlte.Permission_Api_objects', verbose_name='action_name'),
        ),
        migrations.AddField(
            model_name='permission',
            name='resources',
            field=models.ManyToManyField(blank=True, to='adminlte.Resource', verbose_name='\u8d44\u6e90'),
        ),
        migrations.AddField(
            model_name='groups',
            name='group_api_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='group_set_api', related_query_name=b'group_api', to='adminlte.Permission_Api_Action', verbose_name='\u6743\u9650\u7ba1\u7406'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user_api_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set_api', related_query_name=b'user_api', to='adminlte.Permission_Api_Action', verbose_name='\u6743\u9650\u7ba1\u7406'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions'),
        ),
    ]
