# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-04 16:27
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('adminlte', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LteUser',
            fields=[
            ],
            options={
                'verbose_name': '\u7528\u6237',
                'proxy': True,
                'verbose_name_plural': '\u7528\u6237',
            },
            bases=('crm.userprofile',),
        ),
        migrations.AddField(
            model_name='systemconfig',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u6570\u636e\u521b\u5efa\u4eba'),
        ),
        migrations.AddField(
            model_name='systemconfig',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='adminlte.SystemConfig', verbose_name='\u7236\u914d\u7f6e\u9879'),
        ),
        migrations.AddField(
            model_name='resource',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u6570\u636e\u521b\u5efa\u4eba'),
        ),
        migrations.AddField(
            model_name='permission',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u6570\u636e\u521b\u5efa\u4eba'),
        ),
        migrations.AddField(
            model_name='permission',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_permission', to='adminlte.LteGroup', verbose_name='\u89d2\u8272'),
        ),
        migrations.AddField(
            model_name='permission',
            name='menus',
            field=models.ManyToManyField(blank=True, to='adminlte.Menu', verbose_name='\u83dc\u5355'),
        ),
        migrations.AddField(
            model_name='permission',
            name='resources',
            field=models.ManyToManyField(blank=True, to='adminlte.Resource', verbose_name='\u8d44\u6e90'),
        ),
        migrations.AddField(
            model_name='menu',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u6570\u636e\u521b\u5efa\u4eba'),
        ),
        migrations.AddField(
            model_name='menu',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='adminlte.Menu', verbose_name='\u4e0a\u7ea7\u83dc\u5355'),
        ),
    ]
