# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-07 10:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminlte', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_permission', to='adminlte.Groups', verbose_name='\u89d2\u8272'),
        ),
        migrations.AlterField(
            model_name='permission_api_action',
            name='Type',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'get'), (1, 'post')], null=True, verbose_name='\u8bf7\u6c42\u7c7b\u578b'),
        ),
    ]
