# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-18 15:29
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('adminlte', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='\u6570\u636e\u521b\u5efa\u65f6\u95f4')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='\u6570\u636e\u66f4\u65b0\u65f6\u95f4')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='\u6570\u636e\u5220\u9664\u65f6\u95f4')),
                ('Message', models.TextField(blank=True, help_text='\u77ed\u4fe1\u7684json \u63a5\u53e3 \u7528\u4e8e\u76f4\u63a5\u7ed9\u524d\u7aef.\u52ff\u52a8!!!!', null=True, verbose_name='json\u63a5\u53e3')),
                ('Status', models.PositiveSmallIntegerField(choices=[(0, '\u672a\u8bfb'), (1, '\u5df2\u8bfb'), (2, '\u8349\u7a3f'), (3, '\u56de\u6536\u7ad9'), (99, '\u5220\u9664')], db_index=True, default=0, verbose_name='\u72b6\u6001')),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u6570\u636e\u66f4\u65b0\u4eba')),
                ('receive_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receive_user', to=settings.AUTH_USER_MODEL, verbose_name='\u63a5\u6536\u4eba')),
            ],
            options={
                'verbose_name': '\u57fa\u7840-\u6d88\u606f\u4e2d\u5fc3',
                'verbose_name_plural': '\u57fa\u7840-\u6d88\u606f\u4e2d\u5fc3',
            },
        ),
    ]
