# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-22 16:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminlte', '0002_auto_20160507_1010'),
        ('adminlte', '0002_mymessage'),
    ]

    operations = [
    ]
