# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-09 22:10
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_auto_20160109_2210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='valid_end_time',
            field=models.DateTimeField(default=datetime.datetime(2016, 4, 8, 22, 10, 59, 197744, tzinfo=utc)),
        ),
    ]
