# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-09 22:12
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_auto_20160109_2211'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compliant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compliant_type', models.CharField(choices=[(b'compliant', '\u6295\u8bc9'), (b'suggestion', '\u5efa\u8bae')], default=b'compliant', max_length=32, verbose_name='\u9009\u62e9\u7c7b\u578b')),
                ('title', models.CharField(help_text='\u6807\u9898...', max_length=128)),
                ('content', models.TextField(help_text='\u6295\u8bc9\u6216\u5efa\u8bae\u5185\u5bb9....', max_length=1024)),
                ('name', models.CharField(help_text='\u4e0d\u586b\u5219\u4e3a\u533f\u540d\u6295\u8bc9\\\u5efa\u8bae...', max_length=32, verbose_name='\u59d3\u540d')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[(b'unread', '\u672a\u5904\u7406'), (b'sovled', '\u5df2\u5904\u7406'), (b'pending', '\u76ee\u524d\u65e0\u6cd5\u89e3\u51b3')], default=b'unread', max_length=32, verbose_name='\u72b6\u6001')),
                ('comment', models.TextField(blank=True, help_text='\u5904\u7406\u65b9\u6848,\u5fc5\u586b...', null=True, verbose_name='\u5904\u7406\u7ed3\u679c\u5907\u6ce8')),
                ('dealing_time', models.DateTimeField(blank=True, null=True, verbose_name='\u5904\u7406\u65f6\u95f4')),
            ],
            options={
                'verbose_name': '\u5b66\u5458\u6295\u8bc9\\\u5efa\u8bae',
                'verbose_name_plural': '\u5b66\u5458\u6295\u8bc9\\\u5efa\u8bae',
            },
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='valid_end_time',
            field=models.DateTimeField(default=datetime.datetime(2016, 4, 8, 22, 12, 10, 311401, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='compliant',
            name='dealer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u5904\u7406\u4eba'),
        ),
    ]
