# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-17 07:15
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0007_auto_20160110_0444'),
    ]

    operations = [
        migrations.AddField(
            model_name='studyrecord',
            name='note',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='\u5907\u6ce8'),
        ),
        migrations.AlterField(
            model_name='classlist',
            name='course',
            field=models.CharField(choices=[(b'LinuxL1', 'Linux\u4e2d\u9ad8\u7ea7'), (b'LinuxL2', 'Linux\u67b6\u6784\u5e08'), (b'PythonDevOps', 'Python\u81ea\u52a8\u5316\u5f00\u53d1'), (b'PythonDevOps51', 'Python\u81ea\u52a8\u5316\u5f00\u53d1(51\u7f51\u7edc)'), (b'BigDataDev', '\u5927\u6570\u636e\u5f00\u53d1\u8bfe\u7a0b'), (b'Cloud', '\u4e91\u8ba1\u7b97\u8bfe\u7a0b')], max_length=64, verbose_name='\u8bfe\u7a0b\u540d\u79f0'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='course',
            field=models.CharField(choices=[(b'LinuxL1', 'Linux\u4e2d\u9ad8\u7ea7'), (b'LinuxL2', 'Linux\u67b6\u6784\u5e08'), (b'PythonDevOps', 'Python\u81ea\u52a8\u5316\u5f00\u53d1'), (b'PythonDevOps51', 'Python\u81ea\u52a8\u5316\u5f00\u53d1(51\u7f51\u7edc)'), (b'BigDataDev', '\u5927\u6570\u636e\u5f00\u53d1\u8bfe\u7a0b'), (b'Cloud', '\u4e91\u8ba1\u7b97\u8bfe\u7a0b')], max_length=64, verbose_name='\u54a8\u8be2\u8bfe\u7a0b'),
        ),
        migrations.AlterField(
            model_name='paymentrecord',
            name='course',
            field=models.CharField(choices=[(b'LinuxL1', 'Linux\u4e2d\u9ad8\u7ea7'), (b'LinuxL2', 'Linux\u67b6\u6784\u5e08'), (b'PythonDevOps', 'Python\u81ea\u52a8\u5316\u5f00\u53d1'), (b'PythonDevOps51', 'Python\u81ea\u52a8\u5316\u5f00\u53d1(51\u7f51\u7edc)'), (b'BigDataDev', '\u5927\u6570\u636e\u5f00\u53d1\u8bfe\u7a0b'), (b'Cloud', '\u4e91\u8ba1\u7b97\u8bfe\u7a0b')], max_length=64, verbose_name='\u8bfe\u7a0b\u540d'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='valid_end_time',
            field=models.DateTimeField(default=datetime.datetime(2016, 4, 16, 7, 15, 59, 403470, tzinfo=utc)),
        ),
    ]
