# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-18 14:18
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0009_auto_20151213_0839'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_num', models.IntegerField(help_text='\u6b64\u5904\u586b\u5199\u7b2c\u51e0\u8282\u8bfe\u6216\u7b2c\u51e0\u5929\u8bfe\u7a0b...,\u5fc5\u987b\u4e3a\u6570\u5b57', verbose_name='\u8282\u6b21')),
                ('date', models.DateField(auto_now_add=True, verbose_name='\u4e0a\u8bfe\u65e5\u671f')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.ClassList', verbose_name='\u8bfe\u7a0b')),
            ],
            options={
                'verbose_name': '\u4e0a\u8bfe\u7eaa\u5f55',
                'verbose_name_plural': '\u4e0a\u8bfe\u7eaa\u5f55',
            },
        ),
        migrations.CreateModel(
            name='StudyRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record', models.CharField(choices=[(b'checked', '\u5df2\u7b7e\u5230'), (b'late', '\u8fdf\u5230'), (b'noshow', '\u7f3a\u52e4'), (b'leave_early', '\u65e9\u9000')], default=b'checked', max_length=64, verbose_name='\u4e0a\u8bfe\u7eaa\u5f55')),
                ('score', models.IntegerField(choices=[(100, b'A+'), (90, b'A'), (85, b'B+'), (80, b'B'), (70, b'B-'), (60, b'C+'), (50, b'C'), (40, b'C-'), (0, b'D'), (-1, b'N/A')], default=-1, verbose_name='\u672c\u8282\u5f97\u5206')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('course_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.ConsultRecord', verbose_name='\u7b2c\u51e0\u5929\u8bfe\u7a0b')),
            ],
            options={
                'verbose_name': '\u5b66\u5458\u5b66\u4e60\u7eaa\u5f55',
                'verbose_name_plural': '\u5b66\u5458\u5b66\u4e60\u7eaa\u5f55',
            },
        ),
        migrations.AlterField(
            model_name='customer',
            name='class_list',
            field=models.ManyToManyField(blank=True, to='crm.ClassList', verbose_name='\u5df2\u62a5\u73ed\u7ea7'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='valid_end_time',
            field=models.DateTimeField(default=datetime.datetime(2016, 3, 17, 14, 18, 29, 289534, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='studyrecord',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.Customer', verbose_name='\u5b66\u5458'),
        ),
        migrations.AddField(
            model_name='courserecord',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u8bb2\u5e08'),
        ),
    ]
