# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-27 02:58
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0015_auto_20151227_0257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studyrecord',
            name='score',
            field=models.IntegerField(choices=[(100, b'A+'), (90, b'A'), (85, b'B+'), (80, b'B'), (70, b'B-'), (60, b'C+'), (50, b'C'), (40, b'C-'), (0, b'D'), (-1, b'N/A'), (-100, b'COPY')], default=-1, verbose_name='\u672c\u8282\u6210\u7ee9'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='valid_end_time',
            field=models.DateTimeField(default=datetime.datetime(2016, 3, 26, 2, 58, 43, 583008, tzinfo=utc)),
        ),
    ]
