# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-27 04:23
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0016_auto_20151227_0258'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='stu_id',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='\u5b66\u53f7'),
        ),
        migrations.AlterField(
            model_name='courserecord',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.ClassList', verbose_name='\u73ed\u7ea7(\u8bfe\u7a0b)'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='valid_end_time',
            field=models.DateTimeField(default=datetime.datetime(2016, 3, 26, 4, 23, 59, 433676, tzinfo=utc)),
        ),
    ]
