# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-27 05:24
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0017_auto_20151227_0423'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='consultrecord',
            options={'verbose_name': '\u5ba2\u6237\u54a8\u8be2\u8ddf\u8fdb\u8bb0\u5f55', 'verbose_name_plural': '\u5ba2\u6237\u54a8\u8be2\u8ddf\u8fdb\u8bb0\u5f55'},
        ),
        migrations.AlterModelOptions(
            name='customer',
            options={'verbose_name': '\u5ba2\u6237\u4fe1\u606f\u8868', 'verbose_name_plural': '\u5ba2\u6237\u4fe1\u606f\u8868'},
        ),
        migrations.AddField(
            model_name='classlist',
            name='graduate_date',
            field=models.DateField(blank=True, null=True, verbose_name='\u7ed3\u4e1a\u65e5\u671f'),
        ),
        migrations.AlterField(
            model_name='classlist',
            name='course',
            field=models.CharField(choices=[(b'LinuxL1', 'Linux\u4e2d\u9ad8\u7ea7'), (b'LinuxL2', 'Linux\u67b6\u6784\u5e08'), (b'PythonDevOps', 'Python\u81ea\u52a8\u5316\u5f00\u53d1'), (b'BigDataDev', '\u5927\u6570\u636e\u5f00\u53d1\u8bfe\u7a0b'), (b'Cloud', '\u4e91\u8ba1\u7b97\u8bfe\u7a0b')], max_length=64, verbose_name='\u8bfe\u7a0b\u540d\u79f0'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='course',
            field=models.CharField(choices=[(b'LinuxL1', 'Linux\u4e2d\u9ad8\u7ea7'), (b'LinuxL2', 'Linux\u67b6\u6784\u5e08'), (b'PythonDevOps', 'Python\u81ea\u52a8\u5316\u5f00\u53d1'), (b'BigDataDev', '\u5927\u6570\u636e\u5f00\u53d1\u8bfe\u7a0b'), (b'Cloud', '\u4e91\u8ba1\u7b97\u8bfe\u7a0b')], max_length=64, verbose_name='\u54a8\u8be2\u8bfe\u7a0b'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='customer_note',
            field=models.TextField(help_text='\u5ba2\u6237\u54a8\u8be2\u7684\u5927\u6982\u60c5\u51b5,\u5ba2\u6237\u4e2a\u4eba\u4fe1\u606f\u5907\u6ce8\u7b49...', verbose_name='\u5ba2\u6237\u54a8\u8be2\u5185\u5bb9\u8be6\u60c5'),
        ),
        migrations.AlterField(
            model_name='paymentrecord',
            name='course',
            field=models.CharField(choices=[(b'LinuxL1', 'Linux\u4e2d\u9ad8\u7ea7'), (b'LinuxL2', 'Linux\u67b6\u6784\u5e08'), (b'PythonDevOps', 'Python\u81ea\u52a8\u5316\u5f00\u53d1'), (b'BigDataDev', '\u5927\u6570\u636e\u5f00\u53d1\u8bfe\u7a0b'), (b'Cloud', '\u4e91\u8ba1\u7b97\u8bfe\u7a0b')], max_length=64, verbose_name='\u8bfe\u7a0b\u540d'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='valid_end_time',
            field=models.DateTimeField(default=datetime.datetime(2016, 3, 26, 5, 24, 9, 963992, tzinfo=utc)),
        ),
    ]
