# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-27 07:59
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0018_auto_20151227_0524'),
    ]

    operations = [
        migrations.CreateModel(
            name='Survery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='\u8c03\u67e5\u95ee\u5377\u540d\u79f0')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='\u95ee\u5377\u521b\u5efa\u65e5\u671f')),
                ('by_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.ClassList', verbose_name='\u95ee\u5377\u8c03\u67e5\u73ed\u7ea7')),
            ],
            options={
                'verbose_name': '\u8c03\u67e5\u95ee\u5377',
                'verbose_name_plural': '\u8c03\u67e5\u95ee\u5377',
            },
        ),
        migrations.CreateModel(
            name='SurveryItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='\u6b64\u5904\u586b\u5199\u9700\u8981\u8c03\u67e5\u7684\u95ee\u9898...', max_length=255, unique=True, verbose_name='\u8c03\u67e5\u95ee\u9898')),
                ('date', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '\u8c03\u67e5\u95ee\u5377\u95ee\u9898\u5217\u8868',
                'verbose_name_plural': '\u8c03\u67e5\u95ee\u5377\u95ee\u9898\u5217\u8868',
            },
        ),
        migrations.CreateModel(
            name='SurveryRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(help_text='\u82e5\u662f\u533f\u540d\u95ee\u5377,\u59d3\u540d\u53ef\u4e0d\u586b\u5199', max_length=255, verbose_name='\u5b66\u5458\u59d3\u540d')),
                ('score', models.IntegerField(help_text='\u6253\u5206\u4e3a0\u81f310,0\u4e3a\u975e\u5e38\u4e0d\u6ee1\u610f,10\u4e3a\u975e\u5e38\u6ee1\u610f,\u8bf7\u81ea\u884c\u659f\u914c', verbose_name='\u8bc4\u5206')),
                ('suggestion', models.TextField(blank=True, max_length=1024, null=True, verbose_name='\u5efa\u8bae')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='\u6253\u5206\u65e5\u671f')),
                ('survery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.Survery', verbose_name='\u95ee\u5377')),
                ('survery_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.SurveryItem', verbose_name='\u8c03\u67e5\u9879')),
            ],
            options={
                'verbose_name': '\u8c03\u67e5\u95ee\u5377',
                'verbose_name_plural': '\u8c03\u67e5\u95ee\u5377',
            },
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='valid_end_time',
            field=models.DateTimeField(default=datetime.datetime(2016, 3, 26, 7, 59, 30, 375259, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='survery',
            name='questions',
            field=models.ManyToManyField(to='crm.SurveryItem', verbose_name='\u9009\u62e9\u8981\u8c03\u67e5\u7684\u95ee\u9898\u5217\u8868'),
        ),
    ]
