# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-27 08:06
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0019_auto_20151227_0759'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='surveryrecord',
            options={'verbose_name': '\u95ee\u5377\u8bb0\u5f55', 'verbose_name_plural': '\u95ee\u5377\u8bb0\u5f55'},
        ),
        migrations.AlterField(
            model_name='surveryrecord',
            name='student_name',
            field=models.CharField(blank=True, help_text='\u82e5\u662f\u533f\u540d\u95ee\u5377,\u59d3\u540d\u53ef\u4e0d\u586b\u5199', max_length=255, null=True, verbose_name='\u5b66\u5458\u59d3\u540d'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='valid_end_time',
            field=models.DateTimeField(default=datetime.datetime(2016, 3, 26, 8, 6, 23, 893071, tzinfo=utc)),
        ),
    ]
