# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-27 10:17
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0021_auto_20151227_1011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveryitem',
            name='anwser_type',
            field=models.CharField(choices=[(b'score', b'\xe6\x89\x93\xe5\x88\x86'), (b'multiple', b'\xe5\xa4\x9a\xe9\x80\x89'), (b'single', b'\xe5\x8d\x95\xe9\x80\x89'), (b'suggestion', b'\xe5\xbb\xba\xe8\xae\xae')], default=b'score', max_length=32, verbose_name='\u95ee\u9898\u7c7b\u578b'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='valid_end_time',
            field=models.DateTimeField(default=datetime.datetime(2016, 3, 26, 10, 17, 27, 963840, tzinfo=utc)),
        ),
    ]
