# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-27 13:02
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0023_auto_20151227_1302'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveryrecord',
            name='client_id',
            field=models.CharField(default=b'..', max_length=128, verbose_name='\u5ba2\u6237\u673aid,\u4f1a\u81ea\u52a8\u751f\u6210,\u83ab\u6539'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='valid_end_time',
            field=models.DateTimeField(default=datetime.datetime(2016, 3, 26, 13, 2, 38, 387189, tzinfo=utc)),
        ),
    ]
