# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-29 08:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crm', '0017_auto_20161129_0841'),
    ]

    operations = [
        migrations.CreateModel(
            name='StuAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stu_pwd', models.CharField(max_length=40, verbose_name='密码')),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('stu_name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='crm.Customer', verbose_name='关联对象')),
            ],
            options={
                'verbose_name_plural': '学员认证表',
                'verbose_name': '学员认证表',
            },
        ),
        migrations.CreateModel(
            name='Stutest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='姓名')),
                ('age', models.CharField(max_length=20, verbose_name='年龄')),
            ],
        ),
    ]
