# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-24 11:16
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(choices=[(b'LinuxL1', 'Linux\u4e2d\u9ad8\u7ea7'), (b'LinuxL2', 'Linux\u67b6\u6784\u5e08'), (b'Linux51', 'Linux\u4e2d\u9ad8\u7ea7(51\u7f51\u7edc)'), (b'LinuxL251', 'Linux\u4e2d\u9ad8\u7ea7+\u67b6\u6784\u5408\u6210\u73ed(51\u7f51\u7edc)'), (b'PythonDevOps', 'Python\u81ea\u52a8\u5316\u5f00\u53d1'), (b'PythonFullStack', 'Python\u9ad8\u7ea7\u5168\u6808\u5f00\u53d1'), (b'PythonDevOps51', 'Python\u81ea\u52a8\u5316\u5f00\u53d1(51\u7f51\u7edc)'), (b'PythonFullStack51', 'Python\u5168\u6808\u5f00\u53d1(51\u7f51\u7edc)'), (b'BigDataDev', '\u5927\u6570\u636e\u5f00\u53d1\u8bfe\u7a0b'), (b'Cloud', '\u4e91\u8ba1\u7b97\u8bfe\u7a0b')], max_length=64, verbose_name='\u8bfe\u7a0b\u540d\u79f0')),
                ('semester', models.IntegerField(verbose_name='\u5b66\u671f')),
                ('start_date', models.DateField(verbose_name='\u5f00\u73ed\u65e5\u671f')),
                ('graduate_date', models.DateField(blank=True, null=True, verbose_name='\u7ed3\u4e1a\u65e5\u671f')),
                ('teachers', models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='\u8bb2\u5e08')),
            ],
            options={
                'verbose_name': '\u73ed\u7ea7\u5217\u8868',
                'verbose_name_plural': '\u73ed\u7ea7\u5217\u8868',
            },
        ),
        migrations.CreateModel(
            name='Compliant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compliant_type', models.CharField(choices=[(b'compliant', '\u6295\u8bc9'), (b'suggestion', '\u5efa\u8bae')], default=b'compliant', max_length=32, verbose_name='\u9009\u62e9\u7c7b\u578b')),
                ('title', models.CharField(help_text='\u6807\u9898...', max_length=128)),
                ('content', models.TextField(help_text='\u6295\u8bc9\u6216\u5efa\u8bae\u5185\u5bb9....', max_length=1024)),
                ('name', models.CharField(help_text='\u4e0d\u586b\u5219\u4e3a\u533f\u540d\u6295\u8bc9\\\u5efa\u8bae...', max_length=32, verbose_name='\u59d3\u540d')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65e5\u671f')),
                ('status', models.CharField(choices=[(b'unread', '\u672a\u5904\u7406'), (b'sovled', '\u5df2\u5904\u7406'), (b'pending', '\u76ee\u524d\u65e0\u6cd5\u89e3\u51b3')], default=b'unread', max_length=32, verbose_name='\u72b6\u6001')),
                ('comment', models.TextField(blank=True, help_text='\u5904\u7406\u65b9\u6848,\u5fc5\u586b...', null=True, verbose_name='\u5904\u7406\u7ed3\u679c\u5907\u6ce8')),
                ('dealing_time', models.DateTimeField(blank=True, null=True, verbose_name='\u5904\u7406\u65f6\u95f4')),
                ('dealer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u5904\u7406\u4eba')),
            ],
            options={
                'verbose_name': '\u5b66\u5458\u6295\u8bc9\\\u5efa\u8bae',
                'verbose_name_plural': '\u5b66\u5458\u6295\u8bc9\\\u5efa\u8bae',
            },
        ),
        migrations.CreateModel(
            name='ConsultRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(verbose_name='\u8ddf\u8fdb\u5185\u5bb9...')),
                ('status', models.IntegerField(choices=[(1, '\u8fd1\u671f\u65e0\u62a5\u540d\u8ba1\u5212'), (2, '2\u4e2a\u6708\u5185\u62a5\u540d'), (3, '1\u4e2a\u6708\u5185\u62a5\u540d'), (4, '2\u5468\u5185\u62a5\u540d'), (5, '1\u5468\u5185\u62a5\u540d'), (6, '2\u5929\u5185\u62a5\u540d'), (7, '\u5df2\u62a5\u540d'), (8, '\u5df2\u4ea4\u5168\u6b3e')], help_text='\u9009\u62e9\u5ba2\u6237\u6b64\u65f6\u7684\u72b6\u6001', verbose_name='\u72b6\u6001')),
                ('date', models.DateField(auto_now_add=True, verbose_name='\u8ddf\u8fdb\u65e5\u671f')),
                ('consultant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u8ddf\u8e2a\u4eba')),
            ],
            options={
                'verbose_name': '\u5ba2\u6237\u54a8\u8be2\u8ddf\u8fdb\u8bb0\u5f55',
                'verbose_name_plural': '\u5ba2\u6237\u54a8\u8be2\u8ddf\u8fdb\u8bb0\u5f55',
            },
        ),
        migrations.CreateModel(
            name='CourseRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_num', models.IntegerField(help_text='\u6b64\u5904\u586b\u5199\u7b2c\u51e0\u8282\u8bfe\u6216\u7b2c\u51e0\u5929\u8bfe\u7a0b...,\u5fc5\u987b\u4e3a\u6570\u5b57', verbose_name='\u8282\u6b21')),
                ('date', models.DateField(auto_now_add=True, verbose_name='\u4e0a\u8bfe\u65e5\u671f')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.ClassList', verbose_name='\u73ed\u7ea7(\u8bfe\u7a0b)')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u8bb2\u5e08')),
            ],
            options={
                'verbose_name': '\u4e0a\u8bfe\u7eaa\u5f55',
                'verbose_name_plural': '\u4e0a\u8bfe\u7eaa\u5f55',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qq', models.CharField(help_text='QQ\u53f7\u5fc5\u987b\u552f\u4e00', max_length=64, unique=True)),
                ('qq_name', models.CharField(blank=True, max_length=64, null=True, verbose_name='QQ\u540d\u79f0')),
                ('name', models.CharField(blank=True, max_length=32, null=True, verbose_name='\u59d3\u540d')),
                ('phone', models.BigIntegerField(blank=True, null=True, verbose_name='\u624b\u673a\u53f7')),
                ('stu_id', models.CharField(blank=True, max_length=64, null=True, verbose_name='\u5b66\u53f7')),
                ('source', models.CharField(choices=[(b'qq', 'qq\u7fa4'), (b'referral', '\u5185\u90e8\u8f6c\u4ecb\u7ecd'), (b'51cto', '51cto'), (b'others', '\u5176\u5b83')], default=b'qq', max_length=64, verbose_name='\u5ba2\u6237\u6765\u6e90')),
                ('course', models.CharField(choices=[(b'LinuxL1', 'Linux\u4e2d\u9ad8\u7ea7'), (b'LinuxL2', 'Linux\u67b6\u6784\u5e08'), (b'Linux51', 'Linux\u4e2d\u9ad8\u7ea7(51\u7f51\u7edc)'), (b'LinuxL251', 'Linux\u4e2d\u9ad8\u7ea7+\u67b6\u6784\u5408\u6210\u73ed(51\u7f51\u7edc)'), (b'PythonDevOps', 'Python\u81ea\u52a8\u5316\u5f00\u53d1'), (b'PythonFullStack', 'Python\u9ad8\u7ea7\u5168\u6808\u5f00\u53d1'), (b'PythonDevOps51', 'Python\u81ea\u52a8\u5316\u5f00\u53d1(51\u7f51\u7edc)'), (b'PythonFullStack51', 'Python\u5168\u6808\u5f00\u53d1(51\u7f51\u7edc)'), (b'BigDataDev', '\u5927\u6570\u636e\u5f00\u53d1\u8bfe\u7a0b'), (b'Cloud', '\u4e91\u8ba1\u7b97\u8bfe\u7a0b')], max_length=64, verbose_name='\u54a8\u8be2\u8bfe\u7a0b')),
                ('class_type', models.CharField(choices=[(b'online', '\u7f51\u7edc\u73ed'), (b'offline_weekend', '\u9762\u6388\u73ed(\u5468\u672b)'), (b'offline_fulltime', '\u9762\u6388\u73ed(\u8131\u4ea7)')], max_length=64, verbose_name='\u73ed\u7ea7\u7c7b\u578b')),
                ('customer_note', models.TextField(help_text='\u5ba2\u6237\u54a8\u8be2\u7684\u5927\u6982\u60c5\u51b5,\u5ba2\u6237\u4e2a\u4eba\u4fe1\u606f\u5907\u6ce8\u7b49...', verbose_name='\u5ba2\u6237\u54a8\u8be2\u5185\u5bb9\u8be6\u60c5')),
                ('status', models.CharField(choices=[(b'signed', '\u5df2\u62a5\u540d'), (b'unregistered', '\u672a\u62a5\u540d'), (b'paid_in_full', '\u5b66\u8d39\u5df2\u4ea4\u9f50')], default='unregistered', help_text='\u9009\u62e9\u5ba2\u6237\u6b64\u65f6\u7684\u72b6\u6001', max_length=64, verbose_name='\u72b6\u6001')),
                ('date', models.DateField(auto_now_add=True, verbose_name='\u54a8\u8be2\u65e5\u671f')),
                ('class_list', models.ManyToManyField(blank=True, to='crm.ClassList', verbose_name='\u5df2\u62a5\u73ed\u7ea7')),
                ('consultant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u8bfe\u7a0b\u987e\u95ee')),
                ('referral_from', models.ForeignKey(blank=True, help_text='\u82e5\u6b64\u5ba2\u6237\u662f\u8f6c\u4ecb\u7ecd\u81ea\u5185\u90e8\u5b66\u5458,\u8bf7\u5728\u6b64\u5904\u9009\u62e9\u5185\u90e8\u5b66\u5458\u59d3\u540d', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='internal_referral', to='crm.Customer', verbose_name='\u8f6c\u4ecb\u7ecd\u81ea\u5b66\u5458')),
            ],
            options={
                'verbose_name': '\u5ba2\u6237\u4fe1\u606f\u8868',
                'verbose_name_plural': '\u5ba2\u6237\u4fe1\u606f\u8868',
            },
        ),
        migrations.CreateModel(
            name='PaymentRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(choices=[(b'LinuxL1', 'Linux\u4e2d\u9ad8\u7ea7'), (b'LinuxL2', 'Linux\u67b6\u6784\u5e08'), (b'Linux51', 'Linux\u4e2d\u9ad8\u7ea7(51\u7f51\u7edc)'), (b'LinuxL251', 'Linux\u4e2d\u9ad8\u7ea7+\u67b6\u6784\u5408\u6210\u73ed(51\u7f51\u7edc)'), (b'PythonDevOps', 'Python\u81ea\u52a8\u5316\u5f00\u53d1'), (b'PythonFullStack', 'Python\u9ad8\u7ea7\u5168\u6808\u5f00\u53d1'), (b'PythonDevOps51', 'Python\u81ea\u52a8\u5316\u5f00\u53d1(51\u7f51\u7edc)'), (b'PythonFullStack51', 'Python\u5168\u6808\u5f00\u53d1(51\u7f51\u7edc)'), (b'BigDataDev', '\u5927\u6570\u636e\u5f00\u53d1\u8bfe\u7a0b'), (b'Cloud', '\u4e91\u8ba1\u7b97\u8bfe\u7a0b')], max_length=64, verbose_name='\u8bfe\u7a0b\u540d')),
                ('class_type', models.CharField(choices=[(b'online', '\u7f51\u7edc\u73ed'), (b'offline_weekend', '\u9762\u6388\u73ed(\u5468\u672b)'), (b'offline_fulltime', '\u9762\u6388\u73ed(\u8131\u4ea7)')], max_length=64, verbose_name='\u73ed\u7ea7\u7c7b\u578b')),
                ('pay_type', models.CharField(choices=[(b'deposit', '\u8ba2\u91d1/\u62a5\u540d\u8d39'), (b'tution', '\u5b66\u8d39'), (b'refund', '\u9000\u6b3e')], default=b'deposit', max_length=64, verbose_name='\u8d39\u7528\u7c7b\u578b')),
                ('paid_fee', models.IntegerField(default=0, verbose_name='\u8d39\u7528\u6570\u989d')),
                ('note', models.TextField(blank=True, null=True, verbose_name='\u5907\u6ce8')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='\u4ea4\u6b3e\u65e5\u671f')),
                ('consultant', models.ForeignKey(help_text='\u8c01\u7b7e\u7684\u5355\u5c31\u9009\u8c01', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u8d1f\u8d23\u8001\u5e08')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.Customer', verbose_name='\u5ba2\u6237')),
            ],
            options={
                'verbose_name': '\u4ea4\u6b3e\u7eaa\u5f55',
                'verbose_name_plural': '\u4ea4\u6b3e\u7eaa\u5f55',
            },
        ),
        migrations.CreateModel(
            name='StudentFAQ',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='\u95ee\u9898')),
                ('solution', models.TextField(verbose_name='\u7b54\u6848')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u4f5c\u8005')),
            ],
            options={
                'verbose_name': '\u5b66\u5458\u5e38\u89c1\u95ee\u9898\u6c47\u603b',
                'verbose_name_plural': '\u5b66\u5458\u5e38\u89c1\u95ee\u9898\u6c47\u603b',
            },
        ),
        migrations.CreateModel(
            name='StudyRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record', models.CharField(choices=[(b'checked', '\u5df2\u7b7e\u5230'), (b'late', '\u8fdf\u5230'), (b'noshow', '\u7f3a\u52e4'), (b'leave_early', '\u65e9\u9000')], default=b'checked', max_length=64, verbose_name='\u4e0a\u8bfe\u7eaa\u5f55')),
                ('score', models.IntegerField(choices=[(100, b'A+'), (90, b'A'), (85, b'B+'), (80, b'B'), (70, b'B-'), (60, b'C+'), (50, b'C'), (40, b'C-'), (0, b'D'), (-1, b'N/A'), (-100, b'COPY'), (-1000, b'FAIL')], default=-1, verbose_name='\u672c\u8282\u6210\u7ee9')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('note', models.CharField(blank=True, max_length=255, null=True, verbose_name='\u5907\u6ce8')),
                ('course_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.CourseRecord', verbose_name='\u7b2c\u51e0\u5929\u8bfe\u7a0b')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.Customer', verbose_name='\u5b66\u5458')),
            ],
            options={
                'verbose_name': '\u5b66\u5458\u5b66\u4e60\u7eaa\u5f55',
                'verbose_name_plural': '\u5b66\u5458\u5b66\u4e60\u7eaa\u5f55',
            },
        ),
        migrations.CreateModel(
            name='Survery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='\u8c03\u67e5\u95ee\u5377\u540d\u79f0')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='\u95ee\u5377\u521b\u5efa\u65e5\u671f')),
                ('by_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.ClassList', verbose_name='\u95ee\u5377\u8c03\u67e5\u73ed\u7ea7')),
            ],
            options={
                'verbose_name': '\u8c03\u67e5\u95ee\u5377',
                'verbose_name_plural': '\u8c03\u67e5\u95ee\u5377',
            },
        ),
        migrations.CreateModel(
            name='SurveryItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='\u6b64\u5904\u586b\u5199\u9700\u8981\u8c03\u67e5\u7684\u95ee\u9898...', max_length=255, unique=True, verbose_name='\u8c03\u67e5\u95ee\u9898')),
                ('date', models.DateField(auto_now_add=True)),
                ('anwser_type', models.CharField(choices=[(b'score', b'\xe6\x89\x93\xe5\x88\x86'), (b'multiple', b'\xe5\xa4\x9a\xe9\x80\x89'), (b'single', b'\xe5\x8d\x95\xe9\x80\x89'), (b'suggestion', b'\xe5\xbb\xba\xe8\xae\xae')], default=b'score', max_length=32, verbose_name='\u95ee\u9898\u7c7b\u578b')),
            ],
            options={
                'verbose_name': '\u8c03\u67e5\u95ee\u5377\u95ee\u9898\u5217\u8868',
                'verbose_name_plural': '\u8c03\u67e5\u95ee\u5377\u95ee\u9898\u5217\u8868',
            },
        ),
        migrations.CreateModel(
            name='SurveryRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(blank=True, help_text='\u82e5\u662f\u533f\u540d\u95ee\u5377,\u59d3\u540d\u53ef\u4e0d\u586b\u5199', max_length=255, null=True, verbose_name='\u5b66\u5458\u59d3\u540d')),
                ('score', models.IntegerField(help_text='\u6253\u5206\u4e3a0\u81f310,0\u4e3a\u975e\u5e38\u4e0d\u6ee1\u610f,10\u4e3a\u975e\u5e38\u6ee1\u610f,\u8bf7\u81ea\u884c\u659f\u914c', verbose_name='\u8bc4\u5206')),
                ('suggestion', models.TextField(blank=True, max_length=1024, null=True, verbose_name='\u5efa\u8bae')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='\u6253\u5206\u65e5\u671f')),
                ('client_id', models.CharField(default=b'..', max_length=128, verbose_name='\u5ba2\u6237\u673aid,\u4f1a\u81ea\u52a8\u751f\u6210,\u83ab\u6539')),
                ('survery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.Survery', verbose_name='\u95ee\u5377')),
                ('survery_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.SurveryItem', verbose_name='\u8c03\u67e5\u9879')),
            ],
            options={
                'verbose_name': '\u95ee\u5377\u8bb0\u5f55',
                'verbose_name_plural': '\u95ee\u5377\u8bb0\u5f55',
            },
        ),
        migrations.AddField(
            model_name='survery',
            name='questions',
            field=models.ManyToManyField(to='crm.SurveryItem', verbose_name='\u9009\u62e9\u8981\u8c03\u67e5\u7684\u95ee\u9898\u5217\u8868'),
        ),
        migrations.AddField(
            model_name='consultrecord',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.Customer', verbose_name='\u6240\u54a8\u8be2\u5ba2\u6237'),
        ),
        migrations.AlterUniqueTogether(
            name='studyrecord',
            unique_together=set([('course_record', 'student')]),
        ),
        migrations.AlterUniqueTogether(
            name='courserecord',
            unique_together=set([('course', 'day_num')]),
        ),
        migrations.AlterUniqueTogether(
            name='classlist',
            unique_together=set([('course', 'semester')]),
        ),
    ]
